module.exports = {
  abu_dhabi: {
    scores: [34.0, 32.0, 31.6, 30.0, 28.1, 26.1, 22.1, 22.0, 22.0, 19.1],
    drivers: [
      { driver: "Albon", cost: 38, bonus: 1, points: 14 },
      { driver: "Bottas", cost: 61, bonus: 1, points: 18 },
      { driver: "Fittipaldi", cost: 1, bonus: 5, points: 0 },
      { driver: "Gasly", cost: 22, bonus: 1, points: 6 },
      { driver: "Giovinazzi", cost: 5, bonus: 3.5, points: 0 },
      { driver: "Hamilton", cost: 70, bonus: 1, points: 16 },
      { driver: "Kvyat", cost: 20, bonus: 1, points: 2 },
      { driver: "Latifi", cost: 1, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 19, bonus: 1, points: 0 },
      { driver: "Magnussen", cost: 2, bonus: 5, points: 0 },
      { driver: "Norris", cost: 25, bonus: 1, points: 12 },
      { driver: "Ocon", cost: 27, bonus: 1, points: 3 },
      { driver: "Perez", cost: 25, bonus: 1, points: 0 },
      { driver: "Raikkonnen", cost: 5, bonus: 3.5, points: 1 },
      { driver: "Ricciardo", cost: 36, bonus: 1, points: 8 },
      { driver: "Russell", cost: 7, bonus: 2.5, points: 0 },
      { driver: "Sainz", cost: 25, bonus: 1, points: 10 },
      { driver: "Stroll", cost: 31, bonus: 1, points: 4 },
      { driver: "Verstappen", cost: 56, bonus: 1, points: 20 },
      { driver: "Vettel", cost: 13, bonus: 1, points: 0 },
    ],
  },
  bahrain_ii: {
    scores: [48.3, 40.1, 36.1, 34.4, 15.5, 12.2, 12.0, 10.0, 6.4, 2.1],
    drivers: [
      { driver: "Aitken", cost: 1, bonus: 5, points: 0 },
      { driver: "Albon", cost: 38, bonus: 1, points: 0 },
      { driver: "Bottas", cost: 63, bonus: 1, points: 6 },
      { driver: "Fittipaldi", cost: 1, bonus: 5, points: 0 },
      { driver: "Gasly", cost: 29, bonus: 1, points: 2 },
      { driver: "Giovinazzi", cost: 3, bonus: 4.5, points: 0 },
      { driver: "Kvyat", cost: 21, bonus: 1, points: 8 },
      { driver: "Latifi", cost: 2, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 20, bonus: 1, points: 0 },
      { driver: "Magnussen", cost: 2, bonus: 5, points: 0 },
      { driver: "Norris", cost: 25, bonus: 1, points: 3 },
      { driver: "Ocon", cost: 22, bonus: 1, points: 8 },
      { driver: "Perez", cost: 42, bonus: 1, points: 0 },
      { driver: "Raikkonnen", cost: 5, bonus: 3.5, points: 0 },
      { driver: "Ricciardo", cost: 34, bonus: 1, points: 2 },
      { driver: "Russell", cost: 59, bonus: 1, points: 4 },
      { driver: "Sainz", cost: 28, bonus: 1, points: 4 },
      { driver: "Stroll", cost: 20, bonus: 1, points: 6 },
      { driver: "Verstappen", cost: 62, bonus: 1, points: 0 },
      { driver: "Vettel", cost: 15, bonus: 1, points: 1 },
    ],
  },
  bahrain_i: {
    scores: [32.1, 32.1, 30.4, 30.2, 24.1, 20.1, 20.0, 18.1, 6.7, 3.1],
    drivers: [
      { driver: "Albon", cost: 28, bonus: 1, points: 16 },
      { driver: "Bottas", cost: 61, bonus: 1, points: 6 },
      { driver: "Gasly", cost: 23, bonus: 1, points: 10 },
      { driver: "Giovinazzi", cost: 5, bonus: 3, points: 0 },
      { driver: "Grosjean", cost: 2, bonus: 5, points: 0 },
      { driver: "Hamilton", cost: 74, bonus: 1, points: 20 },
      { driver: "Kvyat", cost: 13, bonus: 1, points: 2 },
      { driver: "Latifi", cost: 2, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 34, bonus: 1, points: 3 },
      { driver: "Magnussen", cost: 2, bonus: 5, points: 0 },
      { driver: "Norris", cost: 23, bonus: 1, points: 14 },
      { driver: "Ocon", cost: 17, bonus: 1, points: 4 },
      { driver: "Perez", cost: 38, bonus: 1, points: 0 },
      { driver: "Raikkonnen", cost: 5, bonus: 3, points: 0 },
      { driver: "Ricciardo", cost: 38, bonus: 1, points: 8 },
      { driver: "Russell", cost: 4, bonus: 3.5, points: 1 },
      { driver: "Sainz", cost: 25, bonus: 1, points: 12 },
      { driver: "Stroll", cost: 22, bonus: 1, points: 0 },
      { driver: "Verstappen", cost: 57, bonus: 1, points: 18 },
      { driver: "Vettel", cost: 15, bonus: 1, points: 0 },
    ],
  },
  turkey: {
    scores: [35.1, 35.1, 35.1, 33.0, 29.2, 26.5, 22.0, 18.0, 9.3, 3.7],
    drivers: [
      { driver: "Albon", cost: 38, bonus: 1, points: 8 },
      { driver: "Bottas", cost: 56, bonus: 1, points: 0 },
      { driver: "Gasly", cost: 31, bonus: 1, points: 0 },
      { driver: "Giovinazzi", cost: 5, bonus: 3, points: 0 },
      { driver: "Grosjean", cost: 1, bonus: 5, points: 0 },
      { driver: "Hamilton", cost: 72, bonus: 1, points: 20 },
      { driver: "Kvyat", cost: 23, bonus: 1, points: 1 },
      { driver: "Latifi", cost: 1, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 35, bonus: 1, points: 14 },
      { driver: "Magnussen", cost: 1, bonus: 5, points: 0 },
      { driver: "Norris", cost: 21, bonus: 1, points: 6 },
      { driver: "Ocon", cost: 18, bonus: 1, points: 2 },
      { driver: "Perez", cost: 29, bonus: 1, points: 18 },
      { driver: "Raikkonnen", cost: 5, bonus: 3, points: 0 },
      { driver: "Ricciardo", cost: 31, bonus: 1, points: 3 },
      { driver: "Russell", cost: 4, bonus: 3.5, points: 0 },
      { driver: "Sainz", cost: 21, bonus: 1, points: 12 },
      { driver: "Stroll", cost: 20, bonus: 1, points: 4 },
      { driver: "Verstappen", cost: 57, bonus: 1, points: 10 },
      { driver: "Vettel", cost: 20, bonus: 1, points: 16 },
    ],
  },
  italy_ii: {
    scores: [44.2, 40.0, 38.8, 30.1, 26.6, 26.0, 23.1, 20.0, 10.3, 6.0],
    drivers: [
      { driver: "Albon", cost: 32, bonus: 1, points: 0 },
      { driver: "Bottas", cost: 60, bonus: 1, points: 18 },
      { driver: "Gasly", cost: 21, bonus: 1, points: 0 },
      { driver: "Giovinazzi", cost: 2, bonus: 4.5, points: 3 },
      { driver: "Grosjean", cost: 2, bonus: 4.5, points: 1 },
      { driver: "Hamilton", cost: 75, bonus: 1, points: 20 },
      { driver: "Kvyat", cost: 12, bonus: 1, points: 14 },
      { driver: "Latifi", cost: 1, bonus: 5, points: 2 },
      { driver: "Leclerc", cost: 33, bonus: 1, points: 12 },
      { driver: "Magnussen", cost: 2, bonus: 4.5, points: 0 },
      { driver: "Norris", cost: 23, bonus: 1, points: 6 },
      { driver: "Ocon", cost: 21, bonus: 1, points: 0 },
      { driver: "Perez", cost: 38, bonus: 1, points: 10 },
      { driver: "Raikkonnen", cost: 5, bonus: 3, points: 4 },
      { driver: "Ricciardo", cost: 37, bonus: 1, points: 16 },
      { driver: "Russell", cost: 3, bonus: 4, points: 0 },
      { driver: "Sainz", cost: 25, bonus: 1, points: 8 },
      { driver: "Stroll", cost: 25, bonus: 1, points: 0 },
      { driver: "Verstappen", cost: 56, bonus: 1, points: 0 },
      { driver: "Vettel", cost: 15, bonus: 1, points: 0 },
    ],
  },
  portugal: {
    scores: [39.0, 35.1, 33.0, 32.1, 32.0, 31.1, 27.0, 19.1, 15.0, 12.0],
    drivers: [
      { driver: "Albon", cost: 32, bonus: 1, points: 1 },
      { driver: "Bottas", cost: 62, bonus: 1, points: 18 },
      { driver: "Gasly", cost: 19, bonus: 1, points: 12 },
      { driver: "Giovinazzi", cost: 4, bonus: 4, points: 0 },
      { driver: "Grosjean", cost: 3, bonus: 4.5, points: 0 },
      { driver: "Hamilton", cost: 74, bonus: 1, points: 20 },
      { driver: "Kvyat", cost: 12, bonus: 1, points: 0 },
      { driver: "Latifi", cost: 2, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 31, bonus: 1, points: 14 },
      { driver: "Magnussen", cost: 3, bonus: 4.5, points: 0 },
      { driver: "Norris", cost: 27, bonus: 1, points: 0 },
      { driver: "Ocon", cost: 21, bonus: 1, points: 6 },
      { driver: "Perez", cost: 35, bonus: 1, points: 8 },
      { driver: "Raikkonnen", cost: 5, bonus: 3.5, points: 2 },
      { driver: "Ricciardo", cost: 38, bonus: 1, points: 4 },
      { driver: "Russell", cost: 4, bonus: 4, points: 0 },
      { driver: "Sainz", cost: 28, bonus: 1, points: 10 },
      { driver: "Stroll", cost: 21, bonus: 1, points: 0 },
      { driver: "Verstappen", cost: 55, bonus: 1, points: 16 },
      { driver: "Vettel", cost: 14, bonus: 1, points: 3 },
    ],
  },
  germany: {
    scores: [42.1, 36.5, 24.0, 22.6, 20.6, 20.2, 16.1, 12.1, 8.6, 0.0],
    drivers: [
      { driver: "Albon", cost: 34, bonus: 1, points: 0 },
      { driver: "Bottas", cost: 59, bonus: 1, points: 0 },
      { driver: "Gasly", cost: 25, bonus: 1, points: 10 },
      { driver: "Giovinazzi", cost: 2, bonus: 5, points: 3 },
      { driver: "Grosjean", cost: 2, bonus: 5, points: 4 },
      { driver: "Hamilton", cost: 73, bonus: 1, points: 20 },
      { driver: "Kvyat", cost: 17, bonus: 1, points: 0 },
      { driver: "Latifi", cost: 2, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 23, bonus: 1, points: 8 },
      { driver: "Magnussen", cost: 2, bonus: 5, points: 0 },
      { driver: "Norris", cost: 28, bonus: 1, points: 0 },
      { driver: "Ocon", cost: 24, bonus: 1, points: 0 },
      { driver: "Perez", cost: 39, bonus: 1, points: 14 },
      { driver: "Raikkonnen", cost: 3, bonus: 4.5, points: 1 },
      { driver: "Ricciardo", cost: 37, bonus: 1, points: 16 },
      { driver: "Russell", cost: 3, bonus: 4.5, points: 0 },
      { driver: "Sainz", cost: 23, bonus: 1, points: 12 },
      { driver: "Stroll", cost: 26, bonus: 1, points: 6 },
      { driver: "Verstappen", cost: 55, bonus: 1, points: 18 },
      { driver: "Vettel", cost: 12, bonus: 1, points: 2 },
    ],
  },
  russia: {
    scores: [34.9, 34.2, 27.5, 25.0, 24.1, 17.3, 16.6, 16.6, 15.0, 12.2],
    drivers: [
      { driver: "Albon", cost: 31, bonus: 1, points: 3 },
      { driver: "Bottas", cost: 63, bonus: 1, points: 20 },
      { driver: "Gasly", cost: 21, bonus: 1, points: 4 },
      { driver: "Giovinazzi", cost: 3, bonus: 4.5, points: 2 },
      { driver: "Grosjean", cost: 3, bonus: 4.5, points: 0 },
      { driver: "Hamilton", cost: 74, bonus: 1, points: 16 },
      { driver: "Kvyat", cost: 14, bonus: 1, points: 6 },
      { driver: "Latifi", cost: 2, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 23, bonus: 1, points: 10 },
      { driver: "Magnussen", cost: 3, bonus: 4.5, points: 1 },
      { driver: "Norris", cost: 29, bonus: 1, points: 0 },
      { driver: "Ocon", cost: 21, bonus: 1, points: 8 },
      { driver: "Perez", cost: 35, bonus: 1, points: 14 },
      { driver: "Raikkonnen", cost: 6, bonus: 3, points: 0 },
      { driver: "Ricciardo", cost: 38, bonus: 1, points: 12 },
      { driver: "Russell", cost: 3, bonus: 4.5, points: 0 },
      { driver: "Sainz", cost: 29, bonus: 1, points: 0 },
      { driver: "Stroll", cost: 31, bonus: 1, points: 0 },
      { driver: "Verstappen", cost: 49, bonus: 1, points: 18 },
      { driver: "Vettel", cost: 14, bonus: 1, points: 0 },
    ],
  },
  tuscany: {
    scores: [46.0, 44.0, 32.1, 24.1, 24.0, 22.0, 20.6, 20.1, 14.0, 6.3],
    drivers: [
      { driver: "Albon", cost: 35, bonus: 1, points: 16 },
      { driver: "Bottas", cost: 61, bonus: 1, points: 18 },
      { driver: "Gasly", cost: 25, bonus: 1, points: 0 },
      { driver: "Giovinazzi", cost: 3, bonus: 4, points: 0 },
      { driver: "Grosjean", cost: 2, bonus: 4.5, points: 1 },
      { driver: "Hamilton", cost: 74, bonus: 1, points: 20 },
      { driver: "Kvyat", cost: 15, bonus: 1, points: 8 },
      { driver: "Latifi", cost: 1, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 18, bonus: 1, points: 6 },
      { driver: "Magnussen", cost: 3, bonus: 4, points: 0 },
      { driver: "Norris", cost: 33, bonus: 1, points: 10 },
      { driver: "Ocon", cost: 22, bonus: 1, points: 0 },
      { driver: "Perez", cost: 35, bonus: 1, points: 12 },
      { driver: "Raikkonnen", cost: 4, bonus: 3, points: 4 },
      { driver: "Ricciardo", cost: 32, bonus: 1, points: 14 },
      { driver: "Russell", cost: 3, bonus: 4, points: 2 },
      { driver: "Sainz", cost: 34, bonus: 1, points: 0 },
      { driver: "Stroll", cost: 28, bonus: 1, points: 0 },
      { driver: "Verstappen", cost: 55, bonus: 1, points: 0 },
      { driver: "Vettel", cost: 8, bonus: 2, points: 3 },
    ],
  },
  italy_i: {
    scores: [44.5, 39.1, 34.1, 34.0, 26.2, 24.1, 19.3, 18.0, 10.1, 5.1],
    drivers: [
      { driver: "Albon", cost: 31, bonus: 1, points: 0 },
      { driver: "Bottas", cost: 61, bonus: 1, points: 12 },
      { driver: "Gasly", cost: 27, bonus: 1, points: 20 },
      { driver: "Giovinazzi", cost: 3, bonus: 4, points: 0 },
      { driver: "Grosjean", cost: 3, bonus: 4, points: 1 },
      { driver: "Hamilton", cost: 74, bonus: 1, points: 8 },
      { driver: "Kvyat", cost: 19, bonus: 1, points: 4 },
      { driver: "Latifi", cost: 2, bonus: 5, points: 2 },
      { driver: "Leclerc", cost: 16, bonus: 1, points: 0 },
      { driver: "Magnussen", cost: 3, bonus: 4, points: 0 },
      { driver: "Norris", cost: 25, bonus: 1, points: 14 },
      { driver: "Ocon", cost: 33, bonus: 1, points: 6 },
      { driver: "Perez", cost: 31, bonus: 1, points: 3 },
      { driver: "Raikkonnen", cost: 3, bonus: 4, points: 0 },
      { driver: "Ricciardo", cost: 40, bonus: 1, points: 10 },
      { driver: "Russell", cost: 3, bonus: 4, points: 0 },
      { driver: "Sainz", cost: 24, bonus: 1, points: 18 },
      { driver: "Stroll", cost: 24, bonus: 1, points: 16 },
      { driver: "Verstappen", cost: 56, bonus: 1, points: 0 },
      { driver: "Vettel", cost: 11, bonus: 1, points: 0 },
    ],
  },
  belgium: {
    scores: [35.6, 32.4, 31.0, 30.4, 28.0, 26.0, 21.1, 20.0, 18.0, 16.4],
    drivers: [
      { driver: "Albon", cost: 32, bonus: 1, points: 10 },
      { driver: "Bottas", cost: 63, bonus: 1, points: 18 },
      { driver: "Gasly", cost: 16, bonus: 1, points: 6 },
      { driver: "Giovinazzi", cost: 2, bonus: 4.5, points: 0 },
      { driver: "Grosjean", cost: 4, bonus: 3, points: 0 },
      { driver: "Hamilton", cost: 78, bonus: 1, points: 20 },
      { driver: "Kvyat", cost: 9, bonus: 1.5, points: 2 },
      { driver: "Latifi", cost: 1, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 36, bonus: 1, points: 0 },
      { driver: "Magnussen", cost: 4, bonus: 3, points: 0 },
      { driver: "Norris", cost: 28, bonus: 1, points: 8 },
      { driver: "Ocon", cost: 19, bonus: 1, points: 12 },
      { driver: "Perez", cost: 40, bonus: 1, points: 3 },
      { driver: "Raikkonnen", cost: 4, bonus: 3, points: 1 },
      { driver: "Ricciardo", cost: 25, bonus: 1, points: 14 },
      { driver: "Russell", cost: 5, bonus: 2, points: 0 },
      { driver: "Sainz", cost: 29, bonus: 1, points: 0 },
      { driver: "Stroll", cost: 34, bonus: 1, points: 4 },
      { driver: "Verstappen", cost: 63, bonus: 1, points: 16 },
      { driver: "Vettel", cost: 28, bonus: 1, points: 0 },
    ],
  },
  spain: {
    scores: [30.0, 23.1, 22.6, 22.2, 12.2, 8.0],
    drivers: [
      { driver: "Albon", cost: 30, bonus: 1, points: 6 },
      { driver: "Bottas", cost: 65, bonus: 1, points: 16 },
      { driver: "Gasly", cost: 13, bonus: 1, points: 4 },
      { driver: "Giovinazzi", cost: 2, bonus: 4.5, points: 0 },
      { driver: "Grosjean", cost: 8, bonus: 2, points: 0 },
      { driver: "Hamilton", cost: 76, bonus: 1, points: 20 },
      { driver: "Kvyat", cost: 7, bonus: 3, points: 1 },
      { driver: "Latifi", cost: 1, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 41, bonus: 1, points: 0 },
      { driver: "Magnussen", cost: 8, bonus: 2, points: 0 },
      { driver: "Norris", cost: 25, bonus: 1, points: 3 },
      { driver: "Ocon", cost: 17, bonus: 1, points: 0 },
      { driver: "Perez", cost: 40, bonus: 1, points: 12 },
      { driver: "Raikkonnen", cost: 3, bonus: 4, points: 0 },
      { driver: "Ricciardo", cost: 26, bonus: 1, points: 2 },
      { driver: "Russell", cost: 6, bonus: 3.5, points: 0 },
      { driver: "Sainz", cost: 28, bonus: 1, points: 10 },
      { driver: "Stroll", cost: 33, bonus: 1, points: 14 },
      { driver: "Verstappen", cost: 61, bonus: 1, points: 18 },
      { driver: "Vettel", cost: 26, bonus: 1, points: 8 },
    ],
  },
  britain_ii: {
    scores: [34.0, 29.1, 27.4, 22.1, 18.3, 14.0, 6.0],
    drivers: [
      { driver: "Albon", cost: 33, bonus: 1, points: 12 },
      { driver: "Bottas", cost: 65, bonus: 1, points: 16 },
      { driver: "Gasly", cost: 12, bonus: 1, points: 2 },
      { driver: "Giovinazzi", cost: 3, bonus: 3.5, points: 0 },
      { driver: "Grosjean", cost: 3, bonus: 3.5, points: 0 },
      { driver: "Hamilton", cost: 78, bonus: 1, points: 18 },
      { driver: "Kvyat", cost: 6, bonus: 2, points: 8 },
      { driver: "Latifi", cost: 1, bonus: 5, points: 3 },
      { driver: "Leclerc", cost: 38, bonus: 1, points: 0 },
      { driver: "Magnussen", cost: 4, bonus: 3, points: 14 },
      { driver: "Norris", cost: 30, bonus: 1, points: 0 },
      { driver: "Ocon", cost: 17, bonus: 1, points: 4 },
      { driver: "Perez", cost: 35, bonus: 1, points: 6 },
      { driver: "Raikkonnen", cost: 3, bonus: 3.5, points: 0 },
      { driver: "Ricciardo", cost: 28, bonus: 1, points: 0 },
      { driver: "Russell", cost: 6, bonus: 2, points: 0 },
      { driver: "Sainz", cost: 30, bonus: 1, points: 0 },
      { driver: "Stroll", cost: 38, bonus: 1, points: 10 },
      { driver: "Verstappen", cost: 58, bonus: 1, points: 20 },
      { driver: "Vettel", cost: 22, bonus: 1, points: 1 },
    ],
  },
  britain_i: {
    scores: [62.1, 60.5, 56.7, 26.6, 25.1, 24.2, 22.1, 5.1],
    drivers: [
      { driver: "Albon", cost: 40, bonus: 1, points: 6 },
      { driver: "Bottas", cost: 65, bonus: 1, points: 2 },
      { driver: "Gasly", cost: 4, bonus: 3.5, points: 8 },
      { driver: "Giovinazzi", cost: 8, bonus: 2, points: 0 },
      { driver: "Grosjean", cost: 4, bonus: 3.5, points: 0 },
      { driver: "Hamilton", cost: 78, bonus: 1, points: 20 },
      { driver: "Hulkenberg", cost: 37, bonus: 1, points: 0 },
      { driver: "Kvyat", cost: 9, bonus: 1.5, points: 0 },
      { driver: "Latifi", cost: 2, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 28, bonus: 1, points: 16 },
      { driver: "Magnussen", cost: 5, bonus: 3, points: 0 },
      { driver: "Norris", cost: 30, bonus: 1, points: 12 },
      { driver: "Ocon", cost: 12, bonus: 1, points: 10 },
      { driver: "Raikkonnen", cost: 3, bonus: 4.5, points: 0 },
      { driver: "Ricciardo", cost: 21, bonus: 1, points: 14 },
      { driver: "Russell", cost: 6, bonus: 2.5, points: 1 },
      { driver: "Sainz", cost: 31, bonus: 1, points: 0 },
      { driver: "Stroll", cost: 44, bonus: 1, points: 4 },
      { driver: "Verstappen", cost: 58, bonus: 1, points: 18 },
      { driver: "Vettel", cost: 26, bonus: 1, points: 3 },
    ],
  },
  hungary: {
    scores: [36.0, 30.8, 28.3, 20.3, 20.0, 20.0, 20.0, 20.0, 14.7, 9.7],
    drivers: [
      { driver: "Albon", cost: 47, bonus: 1, points: 12 },
      { driver: "Bottas", cost: 71, bonus: 1, points: 16 },
      { driver: "Gasly", cost: 8, bonus: 2.5, points: 0 },
      { driver: "Giovinazzi", cost: 10, bonus: 2, points: 0 },
      { driver: "Grosjean", cost: 5, bonus: 3, points: 0 },
      { driver: "Hamilton", cost: 86, bonus: 1, points: 20 },
      { driver: "Kvyat", cost: 12, bonus: 1.5, points: 1 },
      { driver: "Latifi", cost: 1, bonus: 5, points: 0 },
      { driver: "Leclerc", cost: 30, bonus: 1, points: 2 },
      { driver: "Magnussen", cost: 5, bonus: 3, points: 3 },
      { driver: "Norris", cost: 36, bonus: 1, points: 0 },
      { driver: "Ocon", cost: 17, bonus: 1, points: 0 },
      { driver: "Perez", cost: 45, bonus: 1, points: 8 },
      { driver: "Raikkonnen", cost: 5, bonus: 3, points: 0 },
      { driver: "Ricciardo", cost: 20, bonus: 1, points: 6 },
      { driver: "Russell", cost: 3, bonus: 4.5, points: 0 },
      { driver: "Sainz", cost: 38, bonus: 1, points: 4 },
      { driver: "Stroll", cost: 34, bonus: 1, points: 14 },
      { driver: "Verstappen", cost: 66, bonus: 1, points: 18 },
      { driver: "Vettel", cost: 30, bonus: 1, points: 10 },
    ],
  },
};
